print("am comming to class today")
print("am comming to class today")
print("am comming to class today")
print("am comming to class today")
print("am comming to class today")
print("am comming to class today")
print("am comming to class today")